apiVersion: v1
kind: Service
metadata:
  name: menu
spec:
  selector:
    app: menu
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu
  labels:
    app: menu
spec:
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
        - name: menu
          image: ${registryURL}/h2o.app.menu:501
          env:
            - name: H2OGateWay
              valueFrom:
                configMapKeyRef:
                  name: menu
                  key: H2OGateWay
            - name: H2OApplicationHost
              valueFrom:
                configMapKeyRef:
                  name: menu
                  key: H2OApplicationHost
            - name: ListenUrls__0
              valueFrom:
                configMapKeyRef:
                  name: menu
                  key: ListenUrls
            - name: LogFileMinLevel
              valueFrom:
                configMapKeyRef:
                  name: menu
                  key: LogFileMinLevel
            - name: LogFileDirectory
              valueFrom:
                configMapKeyRef:
                  name: menu
                  key: LogFileDirectory
            - name: LogConsoleMinLevel
              valueFrom:
                configMapKeyRef:
                  name: menu
                  key: LogConsoleMinLevel
            - name: EnableAudienceChangeWithoutReauthenticationForKeycloak
              valueFrom:
                configMapKeyRef:
                  name: menu
                  key: EnableAudienceChangeWithoutReauthenticationForKeycloak
          readinessProbe:
            httpGet:
              path: /api/microservice/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/microservice/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: menu
data:
  H2OGateWay: 'http://gateway:8080/'
  ListenUrls: 'http://0.0.0.0:8080/'
  H2OApplicationHost: 'http://menu:8080'
  LogFileMinLevel: 'Info'
  LogFileDirectory: '/var/log/hop'
  LogConsoleMinLevel: ''
  EnableAudienceChangeWithoutReauthenticationForKeycloak: ''
