apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# ja resursu kopa
resources:
  - h2o.app.absencecalendar.yaml
  - h2o.app.acquaint.yaml
  - h2o.app.advanceexpense.yaml
  - h2o.app.antra.license.yaml
  - h2o.app.antra.yaml
  - h2o.app.attachment.yaml
  - h2o.app.auth.yaml
  - h2o.app.businesstrip.yaml
  - h2o.app.clientapplications.yaml
  - h2o.app.contract.yaml
  - h2o.app.database.yaml
  - h2o.app.department.yaml
  - h2o.app.elmar.yaml
  - h2o.app.feedback.yaml
  - h2o.app.freeform.yaml
  - h2o.app.gateway.yaml
  - h2o.app.horcalendar.yaml
  - h2o.app.horweb.yaml
  - h2o.app.hrreport.yaml
  - h2o.app.image.yaml
  - h2o.app.license.yaml
  - h2o.app.matres.list.yaml
  - h2o.app.menu.yaml
  - h2o.app.metainvoice.list.yaml
  - h2o.app.metainvoice.submit.yaml
  - h2o.app.mhe.yaml
  - h2o.app.notification.yaml
  - h2o.app.order.yaml
  - h2o.app.payout.yaml
  - h2o.app.payslip.yaml
  - h2o.app.persondata.yaml
  - h2o.app.report.yaml
  - h2o.app.settings.yaml
  - h2o.app.staff.yaml
  - h2o.app.stockwriteoff.yaml
  - h2o.app.task.einventory.yaml
  - h2o.app.task.homeinventory.yaml
  - h2o.app.task.matres.yaml
  - h2o.app.task.metainvoice.yaml
  - h2o.app.task.yaml
  - h2o.app.training.yaml
  - h2o.app.vacation.yaml
  - h2o.app.webrouter.yaml
  - h2o.app.workplace.yaml
  - h2o.app.worktimeplanning.yaml
  - h2o.app.worktimetracking.yaml
  - h2o.web.yaml
  - pg_ecr.yaml
  - h2o.app.ftg.yaml
