apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - signature-postgres.yaml
  - signatureauthorize.yaml
  - signatureclient.yaml
  - signatureconfiguration.yaml
  - signatureintegration.yaml
  - signatureperson.yaml
  - signatureworker.yaml
  - dmss-authentication-service.yaml
  - dmss-container-and-signature-service.yaml
  - dmss-archive-services.yaml
  - dmss-archive-services-fallback.yaml

